version: "3.9"
services:
  mukhlish-postgres:
    image: postgres:latest
    container_name: mukhlish-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: strong
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: